version: '3.8'

services:

  backend:
    image: song-quiz-backend
    build:
      context: backend
    env_file:
      - backend/.env
    environment:
      - SPOTIFY_CALLBACK_URL=http://localhost:5001/auth/callback
    volumes:
      - ./backend/.well-known:/app/.well-known

  frontend:
    image: song-quiz-frontend
    build:
      context: frontend

  gateway:
    image: song-quiz-gateway
    build:
      context: gateway
    ports:
      - 5001:4455
